export const defaultDetails = {
  phones: {
    color: "",
    screenSize: 1,
    screenType: "",
    screenBrightness: 1,
    refreshRate: 1,
    operatingSystem: "",
    chipset: "",
    ram: 1,
    storageCapacity: 1,
    sdSlot: false,
    mainCamera: 1,
    frontCamera: 1,
    batteryCapacity: 1,
    wirelessCharging: false,
    weight: 1,
  },
  laptops: {
    color: "",
    model: "",
    screenSize: 1,
    screenType: "",
    screenBrightness: 1,
    refreshRate: 1,
    resolution: "",
    touchScreen: false,
    cpu: "",
    cores: 1,
    threads: 1,
    ram: 1,
    ramType: "",
    storageCapacity: 1,
    gpuType: "",
    gpu: "",
    vram: 1,
    operatingSystem: "",
    keyboardLighting: false,
    weight: 1,
  },
};
